#!/bin/bash

# GitMon - The Git Repository Monitor
# Copyright (C) 2010  Tomas Varaneckas
# http://www.varaneckas.com

# GitMon launcher script

_LINK=$(readlink -n $0)
if [ ! $_LINK ]; then
    _LINK=$0
fi
GITMON_DIR=$(dirname $_LINK) 
if [ ! $GITMON_DIR ]; then
    GITMON_DIR=$(dirname $0)
fi
exec python $GITMON_DIR/gitmon.py "$@"
