#!/bin/bash
_LINK=$(readlink -n $0)
if [ ! $_LINK ]; then
    _LINK=$0
fi
GITMON_DIR=$(dirname $_LINK) 
if [ ! $GITMON_DIR ]; then
    GITMON_DIR=$(dirname $0)
fi
exec python $GITMON_DIR/gitmon.py "$@"
